__Exercise 1: NumPy: Create an array with values ranging from 12 to 38__
        



In [19]:
import numpy as np
arr_val=np.arange(12,38)
print(arr_val)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]


__Exercise 2: Add a border around an existing array__



In [28]:
import numpy as np
original_array=np.ones((3,3))
print("original_array")
print(original_array)
print("0 on the border and 1 inside in the array")
new_array=np.pad(original_array,pad_width=1,mode="constant",constant_values=0)
print(new_array)

original_array
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
0 on the border and 1 inside in the array
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


__Exercise 3: Convert a list and tuple into arrays__


In [34]:
import numpy as np
given_list=[1,2,3,4,5,6,7,8]
list_to_array=np.asarray(given_list)
print(list_to_array)
given_tuple=([8, 4, 6], [1, 2, 3])
tuple_to_array=np.asarray(given_tuple)
print(tuple_to_array)


[1 2 3 4 5 6 7 8]
[[8 4 6]
 [1 2 3]]


__Exercise 4: Convert the values of Centigrade degrees into Fahrenheit degrees__

In [37]:
import numpy as np
sample_values=[0, 12, 45.21, 34, 99.91]
f_values=np.array(sample_values)
print(f_values)
c_values=(5*f_values/9-(32*5)/9)
print(c_values)





[ 0.   12.   45.21 34.   99.91]
[-17.77777778 -11.11111111   7.33888889   1.11111111  37.72777778]


__Exercise 5: Write a NumPy program to find the number of elements of an array, length of one array element in bytes and total bytes consumed by the elements.__

In [43]:
import numpy as np
l=[1,2,3,4]
array=np.array(l,dtype=np.int64)
print(array)
print("size of array",array.size)
print("length of element if array in bytes",array.itemsize)
print("total number of bytes consumed for elements in array",array.nbytes)

[1 2 3 4]
size of array 4
length of element if array in bytes 8
total number of bytes consumed for elements in array 32


__Exercise 6: Get the unique elements of an array__

In [50]:
import numpy as np
x=np.array([10,10,20,20,30,30])
print("unique elements of the array")
np.unique(x)
x=np.array([[1,1],[2,3]])
print("unique elements",np.unique(x))


unique elements of the array
unique elements [1 2 3]


__Exercise 7: Change the dimension of an array__

In [58]:
import numpy as np
array=np.array([1,2,3,4,5,6,7,8,9])
print(array.shape)
print(array.reshape((3,3)))

(9,)
[[1 2 3]
 [4 5 6]
 [7 8 9]]


__Exercise 8: Create a 1-D array of 30 evenly spaced elements between 2.5. and 6.5, inclusive__

In [59]:
import numpy as np
array=np.linspace(2.5,6.5,30)
print(array)

[2.5        2.63793103 2.77586207 2.9137931  3.05172414 3.18965517
 3.32758621 3.46551724 3.60344828 3.74137931 3.87931034 4.01724138
 4.15517241 4.29310345 4.43103448 4.56896552 4.70689655 4.84482759
 4.98275862 5.12068966 5.25862069 5.39655172 5.53448276 5.67241379
 5.81034483 5.94827586 6.0862069  6.22413793 6.36206897 6.5       ]


__Exercise 9: Convert 1-D arrays as columns into a 2-D array__

In [65]:
import numpy as np
array1=np.array([10,20,30])
array2=np.array([40,50,60])
print(np.stack((array1,array2),axis=1))

[[10 40]
 [20 50]
 [30 60]]


__Exercise 10: Create a 5x5 matrix with row values ranging from 0 to 4__

In [72]:
import numpy as np
array=np.zeros((5,5))      [0 0 0 0]  [0 1 2 3 4]
                           [0 0 0 0]
                           [0 0 0 0]
                           [0 0 0 0]
print(array)
array+=np.arange(0,5)
print(array)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


__Exercise 11: Sum of all the multiples of 3 or 5 below 100__

In [90]:
import numpy as np
x=np.arange(1,100)
print(x)
n=x[(x%3==0) | (x%5==0)]
print(n)
print(sum(n))


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96
 97 98 99]
[ 3  5  6  9 10 12 15 18 20 21 24 25 27 30 33 35 36 39 40 42 45 48 50 51
 54 55 57 60 63 65 66 69 70 72 75 78 80 81 84 85 87 90 93 95 96 99]
2318


__Exercise 12: Combine a one and a two dimensional array together and display their elements__


In [107]:
import numpy as np
array1=np.arange(4)
array2=np.arange(8).reshape(2,4)
print("one dimensional array:",array1)
print("two dimensional array:",array2)
for x,y in np.nditer((array1,array2)):
    print("x:y:",x,y)
    

one dimensional array: [0 1 2 3]
two dimensional array: [[0 1 2 3]
 [4 5 6 7]]
x:y: 0 0
x:y: 1 1
x:y: 2 2
x:y: 3 3
x:y: 0 4
x:y: 1 5
x:y: 2 6
x:y: 3 7


In [106]:
import numpy as np
x=np.array([[ 0.42436315, 0.48558583, 0.32924763], [ 0.7439979,0.58220701,0.38213418], [ 0.5097581,0.34528799,0.1563123 ]])
print("original array:",x)

print("Replace all elements of the said array with .5 which are greater than .5")
x[x > .5]=.5
print(x)

original array: [[0.42436315 0.48558583 0.32924763]
 [0.7439979  0.58220701 0.38213418]
 [0.5097581  0.34528799 0.1563123 ]]
Replace all elements of the said array with .5 which are greater than .5
[[0.42436315 0.48558583 0.32924763]
 [0.5        0.5        0.38213418]
 [0.5        0.34528799 0.1563123 ]]


__Exercise 14: Add a new row to an empty numpy array__


In [115]:
import numpy as np
arr=np.empty((0,3),int)
print("empty array:",arr)
arr=np.append(arr,[[10,20,30],[40,50,60]],axis=0)
print("After adding two arrays:",arr)

empty array: []
After adding two arrays: [[10 20 30]
 [40 50 60]]


__Exercise 15: Write a NumPy program to join a sequence of arrays along a new axis.__


In [130]:
import numpy as np
print("original arrays:")
x=np.array([1,2,3])
y=np.array([2,3,4])
print(x)
print(y)
print("arrays along a new axis:")
print(np.vstack((x,y)))
x=np.array([[1],[2],[3]])
y=np.array([[2],[3],[4]])
print("original arrays:")
print(x)
print(y)
print("arrays along new axis")
print(np.vstack((x,y)))


original arrays:
[1 2 3]
[2 3 4]
arrays along a new axis:
[[1 2 3]
 [2 3 4]]
original arrays:
[[1]
 [2]
 [3]]
[[2]
 [3]
 [4]]
arrays along new axis
[[1]
 [2]
 [3]
 [2]
 [3]
 [4]]
